// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjd_D0uS8TWeZwmQvSqb17TFoQyLapdjk',
    appId: '1:548719785018:web:3bb1c41e9c9a422cfe7103',
    messagingSenderId: '548719785018',
    projectId: 'bloodlink-f6231',
    authDomain: 'bloodlink-f6231.firebaseapp.com',
    storageBucket: 'bloodlink-f6231.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCFYSnJDnZs3eHQf-I-guo1OcoDHMhwHQ',
    appId: '1:548719785018:android:1f789c8dd6e38e18fe7103',
    messagingSenderId: '548719785018',
    projectId: 'bloodlink-f6231',
    storageBucket: 'bloodlink-f6231.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL3cQwAC86TtOrgSLpJOPBANKKlRYWgzs',
    appId: '1:548719785018:ios:ec393173dea344f2fe7103',
    messagingSenderId: '548719785018',
    projectId: 'bloodlink-f6231',
    storageBucket: 'bloodlink-f6231.firebasestorage.app',
    iosBundleId: 'com.example.flutterprojects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL3cQwAC86TtOrgSLpJOPBANKKlRYWgzs',
    appId: '1:548719785018:ios:ec393173dea344f2fe7103',
    messagingSenderId: '548719785018',
    projectId: 'bloodlink-f6231',
    storageBucket: 'bloodlink-f6231.firebasestorage.app',
    iosBundleId: 'com.example.flutterprojects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjd_D0uS8TWeZwmQvSqb17TFoQyLapdjk',
    appId: '1:548719785018:web:dee0bcbcbbdbd78cfe7103',
    messagingSenderId: '548719785018',
    projectId: 'bloodlink-f6231',
    authDomain: 'bloodlink-f6231.firebaseapp.com',
    storageBucket: 'bloodlink-f6231.firebasestorage.app',
  );
}
